name: Keith Center
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9873147392645478
title: 'Keith Center: Comedian, Musician, and Performer.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eef2f5'
    - '#5f545a'
    - '#000000'
    - '#b0b4b7'
    - '#d31c18'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
